### ISSUE TITLE
Last Login

### ISSUE THREAD

**Issue by lukewhrit** [ericzty/eve#6]
`scanning: doing scan: scanFn: scany: scan row into struct fields: can't scan into dest[6]: cannot scan NULL into *time.Time`

We need a default value for last login or something

**Comment by lukewhrit** [comment]
Closed by [9f120a1](https://github.com/ericzty/eve/commit/9f120a1030c855aa6e0cb1b4aa68315ae308b528) but perhaps we should come up with a better solution?

**Comment by ericzty** [comment]
make it not nil in the db and give it a default value of now()

**Comment by ericzty** [comment]
ill sort it after the database schema is cleaner

**Comment by lukewhrit** [comment]
In the create user route we give it a default value of `time.Now()` but in the fill schema we're using for testing they don't have any value thus causing the error.

Even though this would be considered an edge case we should see if we can make it so the login route (and specifically where it marshals the row into the Profile struct) not error when last login is missing.
